
# Copyright (c) 2015-2018 Agalmic Ventures LLC (www.agalmicventures.com)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

- name: Creating account
  user:
    name: bartender
    comment: Bartender
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_type: ed25519
  tags:
    - bartender

- name: Cloning SlackBot repository
  git:
    repo: https://github.com/AgalmicVentures/SlackBot.git
    dest: /home/bartender/Code/OpenSource/SlackBot/
  become: yes
  become_user: bartender
  notify:
    - restart Bartender
  tags:
    - bartender

- name: Creating virtual environment
  pip:
    virtualenv: /home/bartender/Code/OpenSource/SlackBot/myenv
    virtualenv_command: pyvenv
    requirements: /home/bartender/Code/OpenSource/SlackBot/requirements.txt
  become: yes
  become_user: bartender
  notify:
    - restart Bartender
  tags:
    - bartender

- name: Checking for Slack token
  stat:
    path: /home/bartender/Code/OpenSource/SlackBot/bartender.token
  become: yes
  become_user: bartender
  register: stat_result
  tags:
    - bartender

- name: Reading a new Slack token
  pause:
    prompt: Enter new slack token
  register: slack_token
  when: not stat_result.stat.exists
  tags:
    - bartender

- name: Writing Slack token to file
  copy:
    content: "{{ slack_token.user_input }}"
    dest: /home/bartender/Code/OpenSource/SlackBot/bartender.token
  become: yes
  become_user: bartender
  when: not stat_result.stat.exists
  tags:
    - bartender

- name: Creating systemd service
  file:
    src: /home/bartender/Code/OpenSource/SlackBot/system/bartender.service
    dest: /lib/systemd/system/bartender.service
    state: link
    force: yes
  tags:
    - bartender

- name: Starting service
  systemd:
    name: bartender
    state: started
    daemon_reload: yes
  tags:
    - bartender
